Externalize `air` dependency + clean-up

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -1,1 +1,11 @@
-air
+#!/usr/bin/env bash
+
+set -e;
+
+air_cmd=$(which air || echo -n);
+if [ -z ${air_cmd} ]; then
+  echo "Could not locate \"air\" binary";
+  exit 1;
+fi
+
+DATABASE_URL=${DATABASE_URL:-"postgres://postgres:postgres@localhost:5432/workout_of_the_day?sslmode=disable"} ${air_cmd};
